import type { Agent, GalleryPhoto, Listing } from "./types";

// Golden-hour / twilight gradients standing in for photography, in the
// spirit of the brand's dusk-skyline palette (slate blue, sand, powder blue).
const GRADIENTS = {
  marinaDusk: "linear-gradient(135deg,#3a5d70,#1F343F 70%,#0F1115)",
  sandGolden: "linear-gradient(135deg,#D9B9A0,#8d6c54 60%,#3a2a1f)",
  downtownFire: "linear-gradient(135deg,#5a3b3b,#1F343F 70%,#0F1115)",
  powderSky: "linear-gradient(135deg,#7BA0B2,#2C537A 65%,#112028)",
  palmBlush: "linear-gradient(135deg,#e8b9a0,#7BA0B2 60%,#1F343F)",
  duneWarm: "linear-gradient(135deg,#EDE8E4,#D9B9A0 55%,#8d6c54)",
  creekTeal: "linear-gradient(135deg,#7BA0B2,#3F555F 60%,#112028)",
  skylineSlate: "linear-gradient(135deg,#586E78,#1F343F 65%,#0F1115)",
  villaGarden: "linear-gradient(135deg,#A7B7BF,#2D4250 60%,#112028)",
  eveningAmber: "linear-gradient(135deg,#D9B9A0,#5a3b3b 60%,#0F1115)",
} as const;

const ROOM_LABELS = [
  "Living room",
  "Primary bedroom",
  "Kitchen",
  "Balcony view",
  "Exterior",
  "Bathroom",
  "Dining area",
  "Pool deck",
];

function gallery(seed: number, ...gradientKeys: (keyof typeof GRADIENTS)[]): GalleryPhoto[] {
  return gradientKeys.map((key, i) => ({
    label: ROOM_LABELS[(seed + i) % ROOM_LABELS.length],
    gradient: GRADIENTS[key],
  }));
}

const AGENTS: Record<string, Agent> = {
  priya: {
    name: "Priya Sharma",
    role: "Senior agent",
    area: "Palm Jumeirah",
    years: 8,
    deals: 300,
    phone: "+971 4 555 0142",
    email: "priya.sharma@bhomes.com",
    gradient: "linear-gradient(135deg,#D9B9A0,#8d6c54)",
  },
  omar: {
    name: "Omar Al-Hashimi",
    role: "Director, off-plan",
    area: "Downtown & Business Bay",
    years: 11,
    deals: 450,
    phone: "+971 4 555 0187",
    email: "omar.alhashimi@bhomes.com",
    gradient: "linear-gradient(135deg,#A4B6C1,#3a5d70)",
  },
  james: {
    name: "James Whitfield",
    role: "Senior agent",
    area: "Dubai Marina & JBR",
    years: 6,
    deals: 210,
    phone: "+971 4 555 0119",
    email: "james.whitfield@bhomes.com",
    gradient: "linear-gradient(135deg,#7BA0B2,#1F343F)",
  },
  fatima: {
    name: "Fatima Al Suwaidi",
    role: "Villas specialist",
    area: "Arabian Ranches & Dubai Hills",
    years: 9,
    deals: 265,
    phone: "+971 4 555 0163",
    email: "fatima.alsuwaidi@bhomes.com",
    gradient: "linear-gradient(135deg,#EDE8E4,#8d6c54)",
  },
  chen: {
    name: "Chen Wei",
    role: "Investment advisor",
    area: "DIFC & Business Bay",
    years: 5,
    deals: 140,
    phone: "+971 4 555 0206",
    email: "chen.wei@bhomes.com",
    gradient: "linear-gradient(135deg,#AAB4CA,#2D4250)",
  },
};

export const LISTINGS: Listing[] = [
  {
    id: "marina-gate-tower-2-24f",
    title: "Marina Gate Tower 2, 24F",
    community: "Dubai Marina",
    subCommunity: "Marina Gate",
    type: "Apartment",
    status: "Ready",
    tag: "Sea view",
    price: 2450000,
    beds: 3,
    baths: 2,
    sqft: 1840,
    description:
      "A high-floor three-bedroom in Marina Gate with unobstructed sea and marina views. Floor-to-ceiling glazing runs the length of the living room, and the building's five-star amenity deck sits two floors below. Walking distance to the Marina Walk and tram.",
    amenities: [
      "Marina view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "24/7 security",
      "Concierge",
      "Balcony",
      "Built-in wardrobes",
    ],
    gradient: GRADIENTS.marinaDusk,
    gallery: gallery(0, "marinaDusk", "skylineSlate", "duneWarm", "powderSky", "creekTeal"),
    agent: AGENTS.james,
    featured: true,
    listedOn: "2026-05-18",
  },
  {
    id: "palm-jumeirah-frond-d-signature-villa",
    title: "Signature Villa, Frond D",
    community: "Palm Jumeirah",
    subCommunity: "Frond D",
    type: "Villa",
    status: "Ready",
    tag: "Beachfront",
    price: 18500000,
    beds: 6,
    baths: 7,
    sqft: 9200,
    description:
      "A beachfront signature villa on Frond D with private sand and a west-facing pool deck built for sunset. Six ensuite bedrooms, a separate staff wing, and a private berth for a small boat. Full renovation completed in 2024.",
    amenities: [
      "Private beach",
      "Private pool",
      "Boat berth",
      "Maids room",
      "Driver's room",
      "Smart home",
      "Landscaped garden",
      "Covered parking (4)",
    ],
    gradient: GRADIENTS.palmBlush,
    gallery: gallery(1, "palmBlush", "sandGolden", "villaGarden", "duneWarm", "powderSky", "eveningAmber"),
    agent: AGENTS.priya,
    featured: true,
    listedOn: "2026-04-02",
  },
  {
    id: "burj-vista-56f-penthouse",
    title: "Burj Vista, 56F Penthouse",
    community: "Downtown Dubai",
    subCommunity: "Burj Vista",
    type: "Penthouse",
    status: "Ready",
    tag: "Hot",
    price: 14200000,
    beds: 4,
    baths: 5,
    sqft: 5180,
    description:
      "A duplex penthouse on the 56th floor with a direct line of sight to Burj Khalifa and the Dubai Fountain. Double-height living room, private lift lobby, and a wraparound terrace built for entertaining.",
    amenities: [
      "Burj Khalifa view",
      "Private lift lobby",
      "Wraparound terrace",
      "Infinity pool access",
      "Gym",
      "Valet parking",
      "Smart home",
      "Study",
    ],
    gradient: GRADIENTS.downtownFire,
    gallery: gallery(2, "downtownFire", "skylineSlate", "eveningAmber", "powderSky", "duneWarm"),
    agent: AGENTS.omar,
    featured: true,
    listedOn: "2026-06-10",
  },
  {
    id: "rimal-4-jbr-2br",
    title: "Rimal 4, Beachside 2BR",
    community: "JBR",
    subCommunity: "Rimal",
    type: "Apartment",
    status: "Ready",
    tag: "Sea view",
    price: 3100000,
    beds: 2,
    baths: 3,
    sqft: 1520,
    description:
      "Steps from The Walk, this two-bedroom in Rimal 4 looks straight out over the Gulf. Recently upgraded kitchen and bathrooms, with full-time beach and pool access included in the service charge.",
    amenities: [
      "Sea view",
      "Beach access",
      "Shared pool",
      "Gym",
      "Kids play area",
      "Covered parking",
      "Balcony",
      "24/7 security",
    ],
    gradient: GRADIENTS.powderSky,
    gallery: gallery(3, "powderSky", "marinaDusk", "duneWarm", "creekTeal"),
    agent: AGENTS.james,
    featured: false,
    listedOn: "2026-03-22",
  },
  {
    id: "executive-towers-business-bay-1br",
    title: "Executive Towers, Canal 1BR",
    community: "Business Bay",
    subCommunity: "Executive Towers",
    type: "Apartment",
    status: "Ready",
    price: 1650000,
    beds: 1,
    baths: 2,
    sqft: 980,
    description:
      "A canal-facing one-bedroom in a well-managed Business Bay tower, five minutes from DIFC. Strong rental history and a low service charge relative to comparable towers on the strip.",
    amenities: [
      "Canal view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "Pet friendly",
      "Built-in wardrobes",
      "Central AC",
    ],
    gradient: GRADIENTS.creekTeal,
    gallery: gallery(4, "creekTeal", "skylineSlate", "powderSky"),
    agent: AGENTS.chen,
    featured: false,
    listedOn: "2026-02-11",
  },
  {
    id: "district-12-jvc-townhouse",
    title: "District 12 Townhouse",
    community: "Jumeirah Village Circle",
    subCommunity: "District 12",
    type: "Townhouse",
    status: "Ready",
    tag: "New",
    price: 2750000,
    beds: 3,
    baths: 4,
    sqft: 2340,
    description:
      "A corner-plot townhouse in District 12 with a private garden and roof terrace. Family-oriented community with its own park, pool, and retail strip within walking distance.",
    amenities: [
      "Private garden",
      "Roof terrace",
      "Shared pool",
      "Maids room",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
    ],
    gradient: GRADIENTS.villaGarden,
    gallery: gallery(5, "villaGarden", "duneWarm", "sandGolden", "skylineSlate"),
    agent: AGENTS.fatima,
    featured: true,
    listedOn: "2026-05-30",
  },
  {
    id: "sidra-3-dubai-hills-villa",
    title: "Sidra 3 Villa",
    community: "Dubai Hills Estate",
    subCommunity: "Sidra",
    type: "Villa",
    status: "Ready",
    tag: "Golf view",
    price: 6900000,
    beds: 5,
    baths: 6,
    sqft: 4520,
    description:
      "A five-bedroom Sidra 3 villa backing onto the Dubai Hills golf course, with an upgraded landscaped garden and a family room opening onto the pool. Close to Dubai Hills Mall and the community park.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Landscaped garden",
      "Maids room",
      "Study",
      "Covered parking (3)",
      "Smart home",
    ],
    gradient: GRADIENTS.duneWarm,
    gallery: gallery(6, "duneWarm", "villaGarden", "sandGolden", "powderSky", "eveningAmber"),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-01-28",
  },
  {
    id: "alma-arabian-ranches-villa",
    title: "Alma Villa, Corner Plot",
    community: "Arabian Ranches",
    subCommunity: "Alma",
    type: "Villa",
    status: "Ready",
    price: 5400000,
    beds: 4,
    baths: 5,
    sqft: 3980,
    description:
      "A corner-plot Alma villa with an oversized garden and a private pool added in 2023. Arabian Ranches' original low-rise charm, with easy access to the polo club and community souk.",
    amenities: [
      "Private pool",
      "Private garden",
      "Maids room",
      "Study",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
    ],
    gradient: GRADIENTS.sandGolden,
    gallery: gallery(7, "sandGolden", "villaGarden", "duneWarm", "eveningAmber"),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2025-12-15",
  },
  {
    id: "index-tower-difc-3br",
    title: "Index Tower, High Floor 3BR",
    community: "DIFC",
    subCommunity: "Index Tower",
    type: "Apartment",
    status: "Ready",
    tag: "Exclusive",
    price: 2900000,
    beds: 3,
    baths: 4,
    sqft: 2050,
    description:
      "A high-floor three-bedroom in Index Tower with skyline views over DIFC and Downtown. Walkable to Gate Avenue's restaurants and galleries, with direct access to the financial district's metro link.",
    amenities: [
      "Skyline view",
      "Shared pool",
      "Gym",
      "Concierge",
      "Valet parking",
      "Study",
      "Central AC",
    ],
    gradient: GRADIENTS.skylineSlate,
    gallery: gallery(0, "skylineSlate", "downtownFire", "powderSky", "creekTeal"),
    agent: AGENTS.chen,
    featured: false,
    listedOn: "2026-04-19",
  },
  {
    id: "central-park-city-walk-2br",
    title: "Central Park, City Walk 2BR",
    community: "City Walk",
    subCommunity: "Central Park",
    type: "Apartment",
    status: "Ready",
    tag: "New",
    price: 3750000,
    beds: 2,
    baths: 3,
    sqft: 1680,
    description:
      "A two-bedroom in Central Park overlooking City Walk's central boulevard. Boutique retail, cinema, and dining all within a five-minute walk, with Downtown ten minutes by car.",
    amenities: [
      "Boulevard view",
      "Shared pool",
      "Gym",
      "Kids play area",
      "Concierge",
      "Covered parking",
      "Balcony",
    ],
    gradient: GRADIENTS.eveningAmber,
    gallery: gallery(1, "eveningAmber", "duneWarm", "powderSky", "skylineSlate"),
    agent: AGENTS.omar,
    featured: false,
    listedOn: "2026-06-01",
  },
  {
    id: "zahra-town-square-townhouse",
    title: "Zahra Townhouse, Town Square",
    community: "Town Square",
    subCommunity: "Zahra",
    type: "Townhouse",
    status: "Ready",
    price: 1950000,
    beds: 3,
    baths: 3,
    sqft: 1980,
    description:
      "An entry-level three-bedroom townhouse in Zahra, Town Square, close to the community's central park and splash pad. Popular with young families for its value relative to JVC and Arabian Ranches.",
    amenities: [
      "Shared pool",
      "Community park",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
      "Central AC",
    ],
    gradient: GRADIENTS.villaGarden,
    gallery: gallery(2, "villaGarden", "duneWarm", "sandGolden"),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2025-11-08",
  },
  {
    id: "redwood-park-jge-villa",
    title: "Redwood Park Villa",
    community: "Jumeirah Golf Estates",
    subCommunity: "Redwood Park",
    type: "Villa",
    status: "Ready",
    tag: "Golf view",
    price: 7800000,
    beds: 5,
    baths: 6,
    sqft: 5240,
    description:
      "A Redwood Park villa on the Fire course, with a double-height entrance hall and a pool terrace facing the fairway. Golf membership options available through the estate's clubhouse.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Landscaped garden",
      "Maids room",
      "Driver's room",
      "Study",
      "Smart home",
    ],
    gradient: GRADIENTS.duneWarm,
    gallery: gallery(3, "duneWarm", "villaGarden", "powderSky", "eveningAmber", "sandGolden"),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-02-27",
  },
  {
    id: "bluewaters-residences-penthouse",
    title: "Bluewaters Residences Penthouse",
    community: "Bluewaters Island",
    subCommunity: "Bluewaters Residences",
    type: "Penthouse",
    status: "Ready",
    tag: "Sea view",
    price: 16800000,
    beds: 4,
    baths: 5,
    sqft: 4680,
    description:
      "A full-floor penthouse on Bluewaters Island with views of Ain Dubai, the Marina skyline, and open sea. Private rooftop terrace with a plunge pool, steps from the island's restaurant row.",
    amenities: [
      "Sea view",
      "Private rooftop terrace",
      "Plunge pool",
      "Concierge",
      "Valet parking",
      "Smart home",
      "Study",
    ],
    gradient: GRADIENTS.powderSky,
    gallery: gallery(4, "powderSky", "marinaDusk", "creekTeal", "duneWarm"),
    agent: AGENTS.james,
    featured: true,
    listedOn: "2026-05-05",
  },
  {
    id: "harbour-views-creek-harbour-1br",
    title: "Harbour Views, Creek Harbour 1BR",
    community: "Dubai Creek Harbour",
    subCommunity: "Harbour Views",
    type: "Apartment",
    status: "Off-plan",
    tag: "Off-plan",
    price: 1450000,
    beds: 1,
    baths: 2,
    sqft: 820,
    description:
      "An off-plan one-bedroom in Harbour Views II with views toward the future Dubai Creek Tower and the Ras Al Khor wildlife sanctuary. Handover expected Q4 2027, on a post-handover payment plan.",
    amenities: [
      "Creek view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "Kids play area",
      "Central AC",
    ],
    gradient: GRADIENTS.creekTeal,
    gallery: gallery(5, "creekTeal", "powderSky", "skylineSlate"),
    agent: AGENTS.omar,
    featured: false,
    listedOn: "2026-06-20",
  },
  {
    id: "emirates-hills-signature-villa",
    title: "Emirates Hills Signature Villa",
    community: "Emirates Hills",
    subCommunity: "Sector E",
    type: "Villa",
    status: "Ready",
    tag: "Exclusive",
    price: 32000000,
    beds: 7,
    baths: 9,
    sqft: 14200,
    description:
      "An architect-designed signature villa on one of Emirates Hills' largest plots, overlooking the Montgomerie golf course. Home cinema, indoor and outdoor pools, and a five-car garage.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Home cinema",
      "Maids room (x2)",
      "Driver's room",
      "Smart home",
      "Covered parking (5)",
      "Landscaped garden",
    ],
    gradient: GRADIENTS.skylineSlate,
    gallery: gallery(6, "skylineSlate", "villaGarden", "duneWarm", "eveningAmber", "sandGolden", "powderSky"),
    agent: AGENTS.priya,
    featured: false,
    listedOn: "2026-03-03",
  },
];

export const COMMUNITIES = Array.from(new Set(LISTINGS.map((l) => l.community))).sort();
export const PROPERTY_TYPES: Listing["type"][] = ["Apartment", "Villa", "Townhouse", "Penthouse"];

export function getListingById(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}

export function getFeaturedListings(limit = 6): Listing[] {
  const featured = LISTINGS.filter((l) => l.featured);
  return (featured.length ? featured : LISTINGS).slice(0, limit);
}
