import type { Agent, GalleryPhoto, Listing } from "./types";
import { propertyPhoto } from "./images";

const ROOM_LABELS = [
  "Living room",
  "Primary bedroom",
  "Kitchen",
  "Balcony view",
  "Exterior",
  "Bathroom",
  "Dining area",
  "Pool deck",
];

function gallery(id: string, count: number): GalleryPhoto[] {
  return Array.from({ length: count }, (_, i) => ({
    label: ROOM_LABELS[i % ROOM_LABELS.length],
    url: propertyPhoto(`${id}-${i}`),
  }));
}

const AGENTS: Record<string, Agent> = {
  priya: {
    name: "Priya Sharma",
    role: "Senior agent",
    area: "Palm Jumeirah",
    years: 8,
    deals: 300,
    phone: "+971 4 555 0142",
    email: "priya.sharma@bhomes.com",
  },
  omar: {
    name: "Omar Al-Hashimi",
    role: "Director, off-plan",
    area: "Downtown & Business Bay",
    years: 11,
    deals: 450,
    phone: "+971 4 555 0187",
    email: "omar.alhashimi@bhomes.com",
  },
  james: {
    name: "James Whitfield",
    role: "Senior agent",
    area: "Dubai Marina & JBR",
    years: 6,
    deals: 210,
    phone: "+971 4 555 0119",
    email: "james.whitfield@bhomes.com",
  },
  fatima: {
    name: "Fatima Al Suwaidi",
    role: "Villas specialist",
    area: "Arabian Ranches & Dubai Hills",
    years: 9,
    deals: 265,
    phone: "+971 4 555 0163",
    email: "fatima.alsuwaidi@bhomes.com",
  },
  chen: {
    name: "Chen Wei",
    role: "Investment advisor",
    area: "DIFC & Business Bay",
    years: 5,
    deals: 140,
    phone: "+971 4 555 0206",
    email: "chen.wei@bhomes.com",
  },
  layla: {
    name: "Layla Haddad",
    role: "Leasing specialist",
    area: "Dubai Marina & JVC",
    years: 4,
    deals: 190,
    phone: "+971 4 555 0231",
    email: "layla.haddad@bhomes.com",
  },
  arjun: {
    name: "Arjun Nair",
    role: "Leasing specialist",
    area: "Business Bay & Downtown",
    years: 3,
    deals: 120,
    phone: "+971 4 555 0248",
    email: "arjun.nair@bhomes.com",
  },
};

const SALE_LISTINGS: Listing[] = [
  {
    id: "marina-gate-tower-2-24f",
    title: "Marina Gate Tower 2, 24F",
    community: "Dubai Marina",
    subCommunity: "Marina Gate",
    type: "Apartment",
    status: "Ready",
    dealType: "Sale",
    tag: "Sea view",
    price: 2450000,
    beds: 3,
    baths: 2,
    sqft: 1840,
    description:
      "A high-floor three-bedroom in Marina Gate with unobstructed sea and marina views. Floor-to-ceiling glazing runs the length of the living room, and the building's five-star amenity deck sits two floors below. Walking distance to the Marina Walk and tram.",
    amenities: [
      "Marina view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "24/7 security",
      "Concierge",
      "Balcony",
      "Built-in wardrobes",
    ],
    photo: propertyPhoto("marina-gate-tower-2-24f"),
    gallery: gallery("marina-gate-tower-2-24f", 5),
    agent: AGENTS.james,
    featured: true,
    listedOn: "2026-05-18",
  },
  {
    id: "palm-jumeirah-frond-d-signature-villa",
    title: "Signature Villa, Frond D",
    community: "Palm Jumeirah",
    subCommunity: "Frond D",
    type: "Villa",
    status: "Ready",
    dealType: "Sale",
    tag: "Beachfront",
    price: 18500000,
    beds: 6,
    baths: 7,
    sqft: 9200,
    description:
      "A beachfront signature villa on Frond D with private sand and a west-facing pool deck built for sunset. Six ensuite bedrooms, a separate staff wing, and a private berth for a small boat. Full renovation completed in 2024.",
    amenities: [
      "Private beach",
      "Private pool",
      "Boat berth",
      "Maids room",
      "Driver's room",
      "Smart home",
      "Landscaped garden",
      "Covered parking (4)",
    ],
    photo: propertyPhoto("palm-jumeirah-frond-d-signature-villa"),
    gallery: gallery("palm-jumeirah-frond-d-signature-villa", 6),
    agent: AGENTS.priya,
    featured: true,
    listedOn: "2026-04-02",
  },
  {
    id: "burj-vista-56f-penthouse",
    title: "Burj Vista, 56F Penthouse",
    community: "Downtown Dubai",
    subCommunity: "Burj Vista",
    type: "Penthouse",
    status: "Ready",
    dealType: "Sale",
    tag: "Hot",
    price: 14200000,
    beds: 4,
    baths: 5,
    sqft: 5180,
    description:
      "A duplex penthouse on the 56th floor with a direct line of sight to Burj Khalifa and the Dubai Fountain. Double-height living room, private lift lobby, and a wraparound terrace built for entertaining.",
    amenities: [
      "Burj Khalifa view",
      "Private lift lobby",
      "Wraparound terrace",
      "Infinity pool access",
      "Gym",
      "Valet parking",
      "Smart home",
      "Study",
    ],
    photo: propertyPhoto("burj-vista-56f-penthouse"),
    gallery: gallery("burj-vista-56f-penthouse", 5),
    agent: AGENTS.omar,
    featured: true,
    listedOn: "2026-06-10",
  },
  {
    id: "rimal-4-jbr-2br",
    title: "Rimal 4, Beachside 2BR",
    community: "JBR",
    subCommunity: "Rimal",
    type: "Apartment",
    status: "Ready",
    dealType: "Sale",
    tag: "Sea view",
    price: 3100000,
    beds: 2,
    baths: 3,
    sqft: 1520,
    description:
      "Steps from The Walk, this two-bedroom in Rimal 4 looks straight out over the Gulf. Recently upgraded kitchen and bathrooms, with full-time beach and pool access included in the service charge.",
    amenities: [
      "Sea view",
      "Beach access",
      "Shared pool",
      "Gym",
      "Kids play area",
      "Covered parking",
      "Balcony",
      "24/7 security",
    ],
    photo: propertyPhoto("rimal-4-jbr-2br"),
    gallery: gallery("rimal-4-jbr-2br", 4),
    agent: AGENTS.james,
    featured: false,
    listedOn: "2026-03-22",
  },
  {
    id: "executive-towers-business-bay-1br",
    title: "Executive Towers, Canal 1BR",
    community: "Business Bay",
    subCommunity: "Executive Towers",
    type: "Apartment",
    status: "Ready",
    dealType: "Sale",
    price: 1650000,
    beds: 1,
    baths: 2,
    sqft: 980,
    description:
      "A canal-facing one-bedroom in a well-managed Business Bay tower, five minutes from DIFC. Strong rental history and a low service charge relative to comparable towers on the strip.",
    amenities: [
      "Canal view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "Pet friendly",
      "Built-in wardrobes",
      "Central AC",
    ],
    photo: propertyPhoto("executive-towers-business-bay-1br"),
    gallery: gallery("executive-towers-business-bay-1br", 3),
    agent: AGENTS.chen,
    featured: false,
    listedOn: "2026-02-11",
  },
  {
    id: "district-12-jvc-townhouse",
    title: "District 12 Townhouse",
    community: "Jumeirah Village Circle",
    subCommunity: "District 12",
    type: "Townhouse",
    status: "Ready",
    dealType: "Sale",
    tag: "New",
    price: 2750000,
    beds: 3,
    baths: 4,
    sqft: 2340,
    description:
      "A corner-plot townhouse in District 12 with a private garden and roof terrace. Family-oriented community with its own park, pool, and retail strip within walking distance.",
    amenities: [
      "Private garden",
      "Roof terrace",
      "Shared pool",
      "Maids room",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
    ],
    photo: propertyPhoto("district-12-jvc-townhouse"),
    gallery: gallery("district-12-jvc-townhouse", 4),
    agent: AGENTS.fatima,
    featured: true,
    listedOn: "2026-05-30",
  },
  {
    id: "sidra-3-dubai-hills-villa",
    title: "Sidra 3 Villa",
    community: "Dubai Hills Estate",
    subCommunity: "Sidra",
    type: "Villa",
    status: "Ready",
    dealType: "Sale",
    tag: "Golf view",
    price: 6900000,
    beds: 5,
    baths: 6,
    sqft: 4520,
    description:
      "A five-bedroom Sidra 3 villa backing onto the Dubai Hills golf course, with an upgraded landscaped garden and a family room opening onto the pool. Close to Dubai Hills Mall and the community park.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Landscaped garden",
      "Maids room",
      "Study",
      "Covered parking (3)",
      "Smart home",
    ],
    photo: propertyPhoto("sidra-3-dubai-hills-villa"),
    gallery: gallery("sidra-3-dubai-hills-villa", 5),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-01-28",
  },
  {
    id: "alma-arabian-ranches-villa",
    title: "Alma Villa, Corner Plot",
    community: "Arabian Ranches",
    subCommunity: "Alma",
    type: "Villa",
    status: "Ready",
    dealType: "Sale",
    price: 5400000,
    beds: 4,
    baths: 5,
    sqft: 3980,
    description:
      "A corner-plot Alma villa with an oversized garden and a private pool added in 2023. Arabian Ranches' original low-rise charm, with easy access to the polo club and community souk.",
    amenities: [
      "Private pool",
      "Private garden",
      "Maids room",
      "Study",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
    ],
    photo: propertyPhoto("alma-arabian-ranches-villa"),
    gallery: gallery("alma-arabian-ranches-villa", 4),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2025-12-15",
  },
  {
    id: "index-tower-difc-3br",
    title: "Index Tower, High Floor 3BR",
    community: "DIFC",
    subCommunity: "Index Tower",
    type: "Apartment",
    status: "Ready",
    dealType: "Sale",
    tag: "Exclusive",
    price: 2900000,
    beds: 3,
    baths: 4,
    sqft: 2050,
    description:
      "A high-floor three-bedroom in Index Tower with skyline views over DIFC and Downtown. Walkable to Gate Avenue's restaurants and galleries, with direct access to the financial district's metro link.",
    amenities: [
      "Skyline view",
      "Shared pool",
      "Gym",
      "Concierge",
      "Valet parking",
      "Study",
      "Central AC",
    ],
    photo: propertyPhoto("index-tower-difc-3br"),
    gallery: gallery("index-tower-difc-3br", 4),
    agent: AGENTS.chen,
    featured: false,
    listedOn: "2026-04-19",
  },
  {
    id: "central-park-city-walk-2br",
    title: "Central Park, City Walk 2BR",
    community: "City Walk",
    subCommunity: "Central Park",
    type: "Apartment",
    status: "Ready",
    dealType: "Sale",
    tag: "New",
    price: 3750000,
    beds: 2,
    baths: 3,
    sqft: 1680,
    description:
      "A two-bedroom in Central Park overlooking City Walk's central boulevard. Boutique retail, cinema, and dining all within a five-minute walk, with Downtown ten minutes by car.",
    amenities: [
      "Boulevard view",
      "Shared pool",
      "Gym",
      "Kids play area",
      "Concierge",
      "Covered parking",
      "Balcony",
    ],
    photo: propertyPhoto("central-park-city-walk-2br"),
    gallery: gallery("central-park-city-walk-2br", 4),
    agent: AGENTS.omar,
    featured: false,
    listedOn: "2026-06-01",
  },
  {
    id: "zahra-town-square-townhouse",
    title: "Zahra Townhouse, Town Square",
    community: "Town Square",
    subCommunity: "Zahra",
    type: "Townhouse",
    status: "Ready",
    dealType: "Sale",
    price: 1950000,
    beds: 3,
    baths: 3,
    sqft: 1980,
    description:
      "An entry-level three-bedroom townhouse in Zahra, Town Square, close to the community's central park and splash pad. Popular with young families for its value relative to JVC and Arabian Ranches.",
    amenities: [
      "Shared pool",
      "Community park",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
      "Central AC",
    ],
    photo: propertyPhoto("zahra-town-square-townhouse"),
    gallery: gallery("zahra-town-square-townhouse", 3),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2025-11-08",
  },
  {
    id: "redwood-park-jge-villa",
    title: "Redwood Park Villa",
    community: "Jumeirah Golf Estates",
    subCommunity: "Redwood Park",
    type: "Villa",
    status: "Ready",
    dealType: "Sale",
    tag: "Golf view",
    price: 7800000,
    beds: 5,
    baths: 6,
    sqft: 5240,
    description:
      "A Redwood Park villa on the Fire course, with a double-height entrance hall and a pool terrace facing the fairway. Golf membership options available through the estate's clubhouse.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Landscaped garden",
      "Maids room",
      "Driver's room",
      "Study",
      "Smart home",
    ],
    photo: propertyPhoto("redwood-park-jge-villa"),
    gallery: gallery("redwood-park-jge-villa", 5),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-02-27",
  },
  {
    id: "bluewaters-residences-penthouse",
    title: "Bluewaters Residences Penthouse",
    community: "Bluewaters Island",
    subCommunity: "Bluewaters Residences",
    type: "Penthouse",
    status: "Ready",
    dealType: "Sale",
    tag: "Sea view",
    price: 16800000,
    beds: 4,
    baths: 5,
    sqft: 4680,
    description:
      "A full-floor penthouse on Bluewaters Island with views of Ain Dubai, the Marina skyline, and open sea. Private rooftop terrace with a plunge pool, steps from the island's restaurant row.",
    amenities: [
      "Sea view",
      "Private rooftop terrace",
      "Plunge pool",
      "Concierge",
      "Valet parking",
      "Smart home",
      "Study",
    ],
    photo: propertyPhoto("bluewaters-residences-penthouse"),
    gallery: gallery("bluewaters-residences-penthouse", 4),
    agent: AGENTS.james,
    featured: true,
    listedOn: "2026-05-05",
  },
  {
    id: "harbour-views-creek-harbour-1br",
    title: "Harbour Views, Creek Harbour 1BR",
    community: "Dubai Creek Harbour",
    subCommunity: "Harbour Views",
    type: "Apartment",
    status: "Off-plan",
    dealType: "Sale",
    tag: "Off-plan",
    price: 1450000,
    beds: 1,
    baths: 2,
    sqft: 820,
    description:
      "An off-plan one-bedroom in Harbour Views II with views toward the future Dubai Creek Tower and the Ras Al Khor wildlife sanctuary. Handover expected Q4 2027, on a post-handover payment plan.",
    amenities: [
      "Creek view",
      "Shared pool",
      "Gym",
      "Covered parking",
      "Kids play area",
      "Central AC",
    ],
    photo: propertyPhoto("harbour-views-creek-harbour-1br"),
    gallery: gallery("harbour-views-creek-harbour-1br", 3),
    agent: AGENTS.omar,
    featured: false,
    listedOn: "2026-06-20",
  },
  {
    id: "emirates-hills-signature-villa",
    title: "Emirates Hills Signature Villa",
    community: "Emirates Hills",
    subCommunity: "Sector E",
    type: "Villa",
    status: "Ready",
    dealType: "Sale",
    tag: "Exclusive",
    price: 32000000,
    beds: 7,
    baths: 9,
    sqft: 14200,
    description:
      "An architect-designed signature villa on one of Emirates Hills' largest plots, overlooking the Montgomerie golf course. Home cinema, indoor and outdoor pools, and a five-car garage.",
    amenities: [
      "Golf course view",
      "Private pool",
      "Home cinema",
      "Maids room (x2)",
      "Driver's room",
      "Smart home",
      "Covered parking (5)",
      "Landscaped garden",
    ],
    photo: propertyPhoto("emirates-hills-signature-villa"),
    gallery: gallery("emirates-hills-signature-villa", 6),
    agent: AGENTS.priya,
    featured: false,
    listedOn: "2026-03-03",
  },
];

const RENT_LISTINGS: Listing[] = [
  {
    id: "al-nahda-2-family-1bhk",
    title: "Family 1BHK Near Pond Park",
    community: "Business Bay",
    subCommunity: "Executive Towers",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Unfurnished",
    rentFrequency: "Yearly",
    tag: "Chiller free",
    price: 55000,
    beds: 1,
    baths: 2,
    sqft: 871,
    description:
      "A bright one-bedroom close to Business Bay's canal promenade, with kitchen appliances included and chiller charges covered by the landlord. Available immediately, flexible on cheque count.",
    amenities: [
      "Shared pool",
      "Gym",
      "Covered parking",
      "Built-in wardrobes",
      "Central AC",
      "Pet friendly",
    ],
    photo: propertyPhoto("al-nahda-2-family-1bhk"),
    gallery: gallery("al-nahda-2-family-1bhk", 4),
    agent: AGENTS.arjun,
    featured: true,
    listedOn: "2026-06-12",
  },
  {
    id: "marina-gate-1-2br-rent",
    title: "Marina Gate 1, Sea View 2BR",
    community: "Dubai Marina",
    subCommunity: "Marina Gate",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Furnished",
    rentFrequency: "Yearly",
    tag: "Sea view",
    price: 145000,
    beds: 2,
    baths: 3,
    sqft: 1380,
    description:
      "A fully furnished two-bedroom with unobstructed sea views, available for immediate move-in. Building amenities include an infinity pool, spa, and direct mall access.",
    amenities: [
      "Sea view",
      "Shared pool",
      "Gym",
      "Concierge",
      "Covered parking",
      "Balcony",
      "Smart home",
    ],
    photo: propertyPhoto("marina-gate-1-2br-rent"),
    gallery: gallery("marina-gate-1-2br-rent", 4),
    agent: AGENTS.layla,
    featured: true,
    listedOn: "2026-06-25",
  },
  {
    id: "jvc-district-14-studio",
    title: "Modern Studio, District 14",
    community: "Jumeirah Village Circle",
    subCommunity: "District 14",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Furnished",
    rentFrequency: "Yearly",
    tag: "New",
    price: 42000,
    beds: 0,
    baths: 1,
    sqft: 480,
    description:
      "A compact, fully furnished studio in a newly handed-over JVC building. Great starter rental with a rooftop pool and gym, and easy access to Circle Mall.",
    amenities: ["Shared pool", "Gym", "Covered parking", "Central AC", "Built-in wardrobes"],
    photo: propertyPhoto("jvc-district-14-studio"),
    gallery: gallery("jvc-district-14-studio", 3),
    agent: AGENTS.layla,
    featured: false,
    listedOn: "2026-05-14",
  },
  {
    id: "downtown-boulevard-central-2br",
    title: "Boulevard Central, Fountain View 2BR",
    community: "Downtown Dubai",
    subCommunity: "Boulevard Central",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Partly furnished",
    rentFrequency: "Yearly",
    tag: "Fountain view",
    price: 195000,
    beds: 2,
    baths: 3,
    sqft: 1420,
    description:
      "A partly furnished two-bedroom overlooking the Dubai Fountain, in a low-density Boulevard Central building. Walkable to Dubai Mall and the Burj Khalifa entrance.",
    amenities: [
      "Fountain view",
      "Shared pool",
      "Gym",
      "Concierge",
      "Valet parking",
      "Study",
    ],
    photo: propertyPhoto("downtown-boulevard-central-2br"),
    gallery: gallery("downtown-boulevard-central-2br", 4),
    agent: AGENTS.arjun,
    featured: true,
    listedOn: "2026-06-08",
  },
  {
    id: "arabian-ranches-mirador-4br",
    title: "Mirador Villa, Landscaped Garden 4BR",
    community: "Arabian Ranches",
    subCommunity: "Mirador",
    type: "Villa",
    status: "Ready",
    dealType: "Rent",
    furnished: "Unfurnished",
    rentFrequency: "Yearly",
    tag: "Single row",
    price: 260000,
    beds: 4,
    baths: 5,
    sqft: 3600,
    description:
      "A single-row Mirador villa with a mature, landscaped garden and private pool, available for a long-term family let. Close to the community's schools and equestrian centre.",
    amenities: [
      "Private pool",
      "Private garden",
      "Maids room",
      "Covered parking (2)",
      "Built-in wardrobes",
      "Pet friendly",
    ],
    photo: propertyPhoto("arabian-ranches-mirador-4br"),
    gallery: gallery("arabian-ranches-mirador-4br", 4),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-04-30",
  },
  {
    id: "jbr-amwaj-3br-rent",
    title: "Amwaj 4, Beachfront 3BR",
    community: "JBR",
    subCommunity: "Amwaj",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Furnished",
    rentFrequency: "Yearly",
    tag: "Beachfront",
    price: 220000,
    beds: 3,
    baths: 4,
    sqft: 2050,
    description:
      "A furnished three-bedroom directly on The Walk, with full beach and pool access. Short walk to The Beach mall and the tram. Available for a minimum one-year let.",
    amenities: [
      "Sea view",
      "Beach access",
      "Shared pool",
      "Gym",
      "Kids play area",
      "Covered parking",
    ],
    photo: propertyPhoto("jbr-amwaj-3br-rent"),
    gallery: gallery("jbr-amwaj-3br-rent", 4),
    agent: AGENTS.layla,
    featured: false,
    listedOn: "2026-05-22",
  },
  {
    id: "difc-central-park-1br-rent",
    title: "DIFC, Gate Avenue-Adjacent 1BR",
    community: "DIFC",
    subCommunity: "Central Park Towers",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Unfurnished",
    rentFrequency: "Yearly",
    tag: "Skyline view",
    price: 98000,
    beds: 1,
    baths: 2,
    sqft: 950,
    description:
      "A one-bedroom in DIFC's Central Park Towers, unfurnished with premium fittings throughout. Walking distance to Gate Avenue and the financial district's metro link.",
    amenities: ["Skyline view", "Shared pool", "Gym", "Concierge", "Valet parking"],
    photo: propertyPhoto("difc-central-park-1br-rent"),
    gallery: gallery("difc-central-park-1br-rent", 3),
    agent: AGENTS.arjun,
    featured: false,
    listedOn: "2026-03-17",
  },
  {
    id: "town-square-hayat-townhouse-rent",
    title: "Hayat Townhouse, Park-Backing 3BR",
    community: "Town Square",
    subCommunity: "Hayat",
    type: "Townhouse",
    status: "Ready",
    dealType: "Rent",
    furnished: "Unfurnished",
    rentFrequency: "Yearly",
    price: 115000,
    beds: 3,
    baths: 3,
    sqft: 1950,
    description:
      "A park-backing townhouse in Hayat, Town Square, unfurnished and ready for immediate move-in. Community pool, splash park, and retail all within walking distance.",
    amenities: ["Shared pool", "Community park", "Covered parking (2)", "Built-in wardrobes", "Pet friendly"],
    photo: propertyPhoto("town-square-hayat-townhouse-rent"),
    gallery: gallery("town-square-hayat-townhouse-rent", 3),
    agent: AGENTS.layla,
    featured: false,
    listedOn: "2026-02-19",
  },
  {
    id: "city-walk-2br-rent",
    title: "City Walk, Boulevard-Facing 2BR",
    community: "City Walk",
    subCommunity: "Central Park",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Furnished",
    rentFrequency: "Yearly",
    tag: "New",
    price: 175000,
    beds: 2,
    baths: 3,
    sqft: 1650,
    description:
      "A furnished two-bedroom overlooking City Walk's boulevard, with a wraparound balcony. Boutique retail, cinema, and dining all on the doorstep.",
    amenities: ["Boulevard view", "Shared pool", "Gym", "Concierge", "Covered parking", "Balcony"],
    photo: propertyPhoto("city-walk-2br-rent"),
    gallery: gallery("city-walk-2br-rent", 4),
    agent: AGENTS.arjun,
    featured: true,
    listedOn: "2026-06-27",
  },
  {
    id: "dubai-hills-parkway-3br-rent",
    title: "Parkway Views, Park-Facing 3BR",
    community: "Dubai Hills Estate",
    subCommunity: "Parkway Views",
    type: "Apartment",
    status: "Ready",
    dealType: "Rent",
    furnished: "Unfurnished",
    rentFrequency: "Yearly",
    tag: "Park view",
    price: 150000,
    beds: 3,
    baths: 4,
    sqft: 1780,
    description:
      "An unfurnished three-bedroom overlooking Dubai Hills Park, in a low-density building with direct park access. Close to Dubai Hills Mall and the golf course.",
    amenities: ["Park view", "Shared pool", "Gym", "Covered parking", "Kids play area", "Built-in wardrobes"],
    photo: propertyPhoto("dubai-hills-parkway-3br-rent"),
    gallery: gallery("dubai-hills-parkway-3br-rent", 3),
    agent: AGENTS.fatima,
    featured: false,
    listedOn: "2026-01-09",
  },
];

export const LISTINGS: Listing[] = [...SALE_LISTINGS, ...RENT_LISTINGS];

export const SALE_LISTINGS_ONLY = SALE_LISTINGS;
export const RENT_LISTINGS_ONLY = RENT_LISTINGS;

export const COMMUNITIES = Array.from(new Set(LISTINGS.map((l) => l.community))).sort();
export const PROPERTY_TYPES: Listing["type"][] = ["Apartment", "Villa", "Townhouse", "Penthouse"];

export function getListingById(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}

export function getFeaturedListings(limit = 6): Listing[] {
  const featured = SALE_LISTINGS.filter((l) => l.featured);
  return (featured.length ? featured : SALE_LISTINGS).slice(0, limit);
}

export function getFeaturedRentals(limit = 6): Listing[] {
  const featured = RENT_LISTINGS.filter((l) => l.featured);
  return (featured.length ? featured : RENT_LISTINGS).slice(0, limit);
}
